name: CI/CD github actions and docker

on:
    push:
        branches:
            - dev
    pull_request:
        branches: [dev]

# permissions:
#     contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v2

            - name: set docker file
              uses: docker/setup-buildx-action@v1

            - name: login/dockerhub
              uses: docker/login-action@v1
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: devkim1526/steamr:1.0
